### ISSUE TITLE
Error with custom garment obj: "Row index exceeds matrix dimensions" on `laplacianMatrix(_F)`

### ISSUE THREAD

**Issue by alisherakb** [hbertiche/PBNS#1]
Thanks @HugoBA92 for sharing a brilliant work. Resizer model is something we were missing at our project pipeline..

However we are facing an error with `scipy.sparse.coo_matrix.csr_matrix` method when we supply our custom garment OBJ file to train.py (see screenshot attached)
<img width="1106" alt="Screenshot 2022-02-16 at 14 41 03" src="https://user-images.githubusercontent.com/26904008/154248020-b3995a05-a29c-49bf-9081-c41616906c8c.png">

Link to garment: https://drive.google.com/file/d/18WwEWVGCHtxqbq4X4riMmQ_NUIpyFK-o/view?usp=sharing

We couldn't find an anomaly when comparing our garment with your sample. Faces have the same dimension (4).

**Comment by hbertiche** [comment]
I believe I answered this issue to you directly, so I will close this,
please feel free to open it again if this is not the case
