### ISSUE TITLE
Convert fbx to .pkl file

### ISSUE THREAD

**Issue by urstrulybala** [hbertiche/PBNS#10]
I have an SMPL model in FBX format. I need to convert it to pickle (.pkl) format to be able to run the pbns simulation. How can this be done?
Thanks for the help!

**Comment by hbertiche** [comment]
it should be possible to do what you are asking, but it would require expert knowledge about FBX file format, which I do not have,
I suggest to try to obtain the pickle format from SMPL website (https://smpl.is.tue.mpg.de/),
or contacting its authors

**Comment by urstrulybala** [comment]
@hbertiche 
Hi, thanks for the quick response. To ask a simpler question, 
How to obtain the avatars (pickle-smpl versions) like these you have simulated in the following gifs.
https://github.com/hbertiche/PBNS/blob/master/gifs/avatar0.gif
https://github.com/hbertiche/PBNS/blob/master/gifs/avatar1.gif

Thanks

**Comment by hbertiche** [comment]
that's a bit tricky,
we did not use 'pickle-smpl' versions of these avatars (although it is one possibility),
we modified the Data/data.py script to work with different models, we did not release that piece of code,
good news is that soon (can't say when) we will release something like that,
