### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by skeras** [hbertiche/PBNS#3]
Hi, 
   This is a very exciting project, I am going to run this project for test, where can I  download pretrained model? thanks.

**Comment by hbertiche** [comment]
Hi,

apologies for the delayed response,
and thank for showing interest in our work =)

in this work we propose a general methodology to neurally simulate outfits into neural networks,
a single checkpoint, on the other hand, would be specific for a given body and outfit, which is not our final contribution, for this reason, at the moment, we have no plans on releasing pre-trained checkpoints,
