### ISSUE TITLE
*.npy file creation

### ISSUE THREAD

**Issue by hsyntemiz** [hbertiche/PBNS#5]
Thanks for sharing the project details. Amazing work.

It seems trivial, but I couldn't build train.npy & test.npy. I've already had the AMASS dataset, and create an ndarray from the theta values of CMU partition (size of Nx72). But, there seems to be some additional processing that I miss. 

My body meshes have also a some issue. Bodies have kinematically unrealistic poses.

Can you share (or explain) the script to create "*.npy" files?

**Comment by hsyntemiz** [comment]
![Screenshot from 2022-06-06 02-47-09](https://user-images.githubusercontent.com/24231884/172075615-45e3b791-39ee-4c7f-b915-5d0273cc0d5e.png)

My smpl bodies have some issues. Can it be an axis problem?

**Comment by FishWoWater** [comment]
@hsyntemiz 

This is possibly caused by incorrect J_regressor

You can check out the repo `https://github.com/CalciferZh/SMPL`

**Comment by hsyntemiz** [comment]
Thank you @FishWoWater, @hbertiche .
I use preprocess.py given in CalciferZh/SMPL repo. After processing official SMPL model files (*.pkl) with this script, my issues are solved.

![00087](https://user-images.githubusercontent.com/24231884/172696403-ff7799bf-3043-4ec4-b178-e85a5fecc228.jpg)

**Comment by urstrulybala** [comment]
Hi @hsyntemiz , @hbertiche @FishWoWater 
I used the repo (https://github.com/CalciferZh/SMPL) to run preprocess.py on SMPL(for python users) pkl model files. It provides 'model.pkl'. Then running smply_np.py provides smpl.np.obj model. 

But I'm unclear on how to create **train.npy** file that is required to run the train.py script.
Could I get a more detailed explanation. Thanks for your help.

**Comment by urstrulybala** [comment]
@SevadaIskandaryan Hi. I haven't been able to find the solution. Trying to. Let me know too if you crack it.

**Comment by Cao-Cong0** [comment]
> @hbertiche Thanks for the reply. How do I get the Pose data. Is it in Model.pkl file? I could not find anything about pose data in https://smpl.is.tue.mpg.de/. There was only posedirs.npy which had shape (27554, 3, 207).

You can download the CMU dataset from https://amass.is.tue.mpg.de/index.html
The dataset has been updated so the shape is no longer [N,72], it is [N,156] now,  you can just use the data[:,:72] and save it as .npy
