### ISSUE TITLE
Resizing and animating arbitrary garments

### ISSUE THREAD

**Issue by qiqigit** [hbertiche/PBNS#6]
Thank you so much for sharing this interesting work!
I'm wondering if I can resize and animate an arbitrary garment mesh acquired by 3D scanning with your model.

**Comment by hbertiche** [comment]
Hi,

Thanks for your interes tin our work =)

yes, our methodology is compatible with arbitrary garment meshes,
there are some limitations, double-sided meshes will not work properly, this also applies to small details on your mesh that are double-sided, like pockets or cuffs,
if this is the case for your garment, try to process it into a single-sided mesh,

I hope this helps
