### ISSUE TITLE
Pre-trained Models (Checkpoints)

### ISSUE THREAD

**Issue by liujl09** [hbertiche/PBNS#8]
Can you share your trained  models for evaluation? Thanks.

**Comment by hbertiche** [comment]
we do not have plans of releasing trained models,

PBNS is devised as a methodology to neurally simulate outfits into neural networks,
this methodology can be applied to any outfit on top of any rigged 3D model,
for this reason, it does not make sense to provide a single specific checkpoint for a given outfit and a given body,

also note PBNS can be trained in a matter of minutes, allowing easy evaluation of the methodology,
I like to encourage people to try and train networks using PBNS methodology with their own outfits,
